### ISSUE TITLE
Communication with dev ZenID is not working

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/enrollment-server#757]
In mobile tokens start, identity verification.
Pick the documents - any allowed combination

Expected results: Proceed to the scanning of documents.
Actual result: Error.

Note the underlying error message on dev environment:

```
Caused by: com.wultra.core.rest.client.base.RestClientException: HTTP GET request failed
        at com.wultra.core.rest.client.base.DefaultRestClient.get(DefaultRestClient.java:251) ~[rest-client-base-1.7.0-SNAPSHOT.jar:na]
        at com.wultra.app.onboardingserver.docverify.zenid.service.ZenidRestApiService.initSdk(ZenidRestApiService.java:224) ~[classes/:1.5.0-SNAPSHOT]
        at com.wultra.app.onboardingserver.docverify.zenid.provider.ZenidDocumentVerificationProvider.initVerificationSdk(ZenidDocumentVerificationProvider.java:339) ~[classes/:1.5.0-SNAPSHOT]
        ... 145 common frames omitted
Caused by: org.springframework.core.codec.DecodingException: JSON decoding error: Unrecognized field "ProcessingTimeMs" (class com.wultra.app.onboardingserver.docverify.zenid.model.api.ZenidWebInitSdkResponse), not marked as ignorable
        at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:273) ~[spring-web-6.0.7.jar:6.0.7]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
```
We should ignore new unrecognized fields.

**Comment by romanstrobl** [comment]
See:
https://github.com/wultra/enrollment-server-wultra/commit/20e508bccd96f1747843288e0e2ca740d80e1df9

The following configuration is missing: `.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)`

**Comment by banterCZ** [comment]
Introduced by #753
